FROM ubuntu:14.04
MAINTAINER cscs

RUN apt-get update                          && \
    apt-get install -y bison            \
                       file             \
                       g++              \
                       gcc              \
                       gfortran         \
                       libibverbs-dev   \
                       make             \
                       wget             \
                    --no-install-recommends

#
# install CUDA 7.0 from packages
#
RUN wget -q -O - http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY | apt-key add - && \
    echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64 /" > /etc/apt/sources.list.d/cuda.list && \
    apt-get update

ENV CUDA_VERSION 7.0
LABEL com.nvidia.cuda.version="7.0"

RUN apt-get install -y --no-install-recommends --force-yes "cuda-toolkit-7.0" gpu-deployment-kit

#
# setup CUDA 7.0
#
RUN echo "/usr/local/cuda/lib" >> /etc/ld.so.conf.d/cuda.conf   && \
    echo "/usr/local/cuda/lib64" >> /etc/ld.so.conf.d/cuda.conf && \
    ldconfig

RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

#RUN mkdir -p /usr/local/nvidia/lib   && \
#    mkdir -p /usr/local/nvidia/lib64

ENV PATH /usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

#
# install MVAPICH2 from source
#
ADD src/mvapich2-2.1.tar.gz /usr/local/src
RUN cd /usr/local/src/mvapich2-2.1                && \
    ./configure --prefix=/usr/local --disable-xrc    \
                --disable-mcast --enable-cuda=basic  \
                --with-cuda=/usr/local/cuda       && \
    make -j4                                      && \
    make install

#
# install OSU Micro-Benchmarks
#
ENV CC gcc
ENV CXX g++
ENV F90 gfortran
ENV MPIF90 mpif90
ADD src/osu-micro-benchmarks-5.3.tar.gz /usr/local/src
RUN cd /usr/local/src/osu-micro-benchmarks-5.3              && \
    ./configure --prefix=/usr/local CC=$( which mpicc )        \
                CXX=$( which mpicxx ) --enable-cuda            \
                --with-cuda-include=/usr/local/cuda/include    \
                --with-cuda-libpath=/usr/local/cuda/lib64   && \
    make -j4                                                && \
    make install

#
# cleanup
#
RUN rm -r /usr/local/src/mvapich2-2.1             && \
    rm -r /usr/local/src/osu-micro-benchmarks-5.3

WORKDIR /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt

CMD ["mpiexec", "-n", "2", "-bind-to", "core", "./osu_bw"]
